### ISSUE TITLE
Task-1

### ISSUE THREAD

**Issue by karnawataman** [GeekHaven/GeekCamp_DESIGN#1]
# Task-1 

> User flow refers to the path a user takes as they navigate through a product or service. It is a visual representation of the series of steps that a user goes through to achieve a particular goal, such as making a purchase or signing up for an account.
> User flows are an essential part of user experience (UX) design, as they help designers understand how users interact with a product or service. By mapping out the user flow, designers can identify potential pain points or areas where users may get stuck, and then make adjustments to improve the overall user experience.

In this task you are supposed to create a user flow for local event discovery app - An app that shows users nearby events and activities based on their location and interests.

> This task is to be done in FigJam

## **Submission Guideline:**

- Create a text file and add your figma link in the text file (name the text file as your github username) and add the text file in the Task-1 folder.

> This task is for 30 points.

## Use the below resources for reference:
https://www.youtube.com/watch?v=RVNuArHH5WM
https://www.figma.com/file/zU47YMPhVhtT1zNVwMl63J/Untitled?node-id=0-1&t=xiirbx8c2w5xVAYa-0

**Comment by nityagupta6** [comment]
This task is for 30 Points!
Use the below resources for reference:
https://www.youtube.com/watch?v=RVNuArHH5WM
https://www.figma.com/file/zU47YMPhVhtT1zNVwMl63J/Untitled?node-id=0-1&t=xiirbx8c2w5xVAYa-0
